// auth
export const AUTH_OK = 'AUTH_OK';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';
// main
export const MAIN_USER_INIT = 'MAIN_USER_INIT';
export const MAIN_ERROR = 'MAIN_ERROR';
export const MAIN_LOGOUT = 'MAIN_LOGOUT';
export const MAIN_USER_HISTORY = 'MAIN_USER_HISTORY';
export const MAIN_USER_LIST = 'MAIN_USER_LIST';
export const MAIN_CREATE_TRANSACTION = 'MAIN_CREATE_TRANSACTION';
export const MAIN_SORT_HISTORY_DOWN = 'MAIN_SORT_HISTORY_DOWN';
export const MAIN_SORT_HISTORY_UP = 'MAIN_SORT_HISTORY_UP';
